CREATE DATABASE Benefit_management;
USE BENEFIT_MANAGEMENT;

CREATE TABLE USERI (
	USERNAME VARCHAR(100) PRIMARY KEY,
    PW VARCHAR(50),
    NUME VARCHAR(50),
    PRENUME VARCHAR(50),
    IS_ADMIN BOOLEAN
);

CREATE TABLE CATEGORII (
	DENUMIRE VARCHAR(50) PRIMARY KEY
);

CREATE TABLE BENEFICII (
	DENUMIRE VARCHAR(50) PRIMARY KEY, 
    DESCRIERE VARCHAR(1000),
    CATEGORIE VARCHAR(50),
	CONSTRAINT FK_BENEFICIU_CATEGORIE FOREIGN KEY (CATEGORIE) REFERENCES CATEGORII (DENUMIRE)
);

